const dictionary = {
  "привет": "hallo",
  "пока": "tschüss",
  "спасибо": "danke",
  "пожалуйста": "bitte",
  "да": "ja",
  "нет": "nein",
  "извините": "entschuldigung",
  "добро пожаловать": "willkommen",
  "как дела?": "wie geht's?",
  "хорошо": "gut",
  "плохо": "schlecht",
  "дом": "das Haus",
  "книга": "das Buch",
  "стол": "der Tisch",
  "стул": "der Stuhl",
  "окно": "das Fenster",
  "дверь": "die Tür",
  "еда": "das Essen",
  "вода": "das Wasser",
  "молоко": "die Milch",
  "чай": "der Tee",
  "кофе": "der Kaffee",
  "собака": "der Hund",
  "кошка": "die Katze",
  "ребёнок": "das Kind",
  "любовь": "die Liebe",
  "деньги": "das Geld",
  "время": "die Zeit",
  "работа": "die Arbeit",
  "школа": "die Schule",
  "семья": "die Familie",
  "друг": "der Freund",
  "подруга": "die Freundin",
  "город": "die Stadt",
  "страна": "das Land",
  "язык": "die Sprache",
  "говорить": "sprechen",
  "понимать": "verstehen",
  "учиться": "lernen",
  "есть": "essen",
  "пить": "trinken",
  "день": "der Tag",
  "ночь": "die Nacht",
  "неделя": "die Woche",
  "месяц": "der Monat",
  "год": "das Jahr",
  "сегодня": "heute",
  "завтра": "morgen",
  "вчера": "gestern",
  "большой": "groß",
  "маленький": "klein",
  "красивый": "schön",
  "уродливый": "hässlich",
  "старый": "alt",
  "молодой": "jung",
  "хороший": "gut",
  "плохой": "schlecht",
  "быстрый": "schnell",
  "медленный": "langsam",
  "здесь": "hier",
  "там": "dort",
  "сейчас": "jetzt",
  "потом": "später",
  "часто": "oft",
  "всегда": "immer",
  "никогда": "nie",
  "много": "viel",
  "мало": "wenig",
  "как": "wie",
  "кто": "wer",
  "что": "was",
  "автомобиль": "das Auto",
  "поезд": "der Zug",
  "работать": "arbeiten",
  "любить": "lieben",
  "знать": "wissen",
  "думать": "denken",
  "идти": "gehen",
  "приходить": "kommen",
  "быть": "sein",
  "иметь": "haben",
  "мочь": "können",
  "хотеть": "wollen",
  "делать": "machen",
  "видеть": "sehen",
  "слышать": "hören",
  "читать": "lesen",
  "писать": "schreiben",
  "сидеть": "sitzen",
  "стоять": "stehen",
  "бежать": "laufen",
  "спать": "schlafen",
  "кушать": "essen",
  "покупать": "kaufen",
  "продавать": "verkaufen",
  "брать": "nehmen",
  "давать": "geben",
  "делить": "teilen",
  "называть": "nennen",
  "звать": "rufen",
  "работник": "der Arbeiter",
  "учитель": "der Lehrer",
  "студент": "der Student",
  "школьник": "der Schüler",
  "профессор": "der Professor",
  "инженер": "der Ingenieur",
  "врач": "der Arzt",
  "журналист": "der Journalist",
  "музыкант": "der Musiker",
  "художник": "der Maler",
  "директор": "der Direktor",
  "менеджер": "der Manager",
  "клиент": "der Kunde",
  "офис": "das Büro",
  "магазин": "das Geschäft",
  "рынок": "der Markt",
  "банк": "die Bank",
  "почта": "das Postamt",
  "билет": "das Ticket",
  "аэропорт": "der Flughafen",
  "такси": "das Taxi",
  "велосипед": "das Fahrrad",
  "улица": "die Straße",
  "площадь": "der Platz",
  "парк": "der Park",
  "деревня": "das Dorf",
  "область": "das Gebiet",
  "страница": "die Seite",
  "карта": "die Karte",
  "знак": "das Zeichen",
  "номер": "die Nummer",
  "вопрос": "die Frage",
  "ответ": "die Antwort",
  "проблема": "das Problem",
  "решение": "die Lösung",
  "пример": "das Beispiel",
  "объяснение": "die Erklärung",
  "учебник": "das Lehrbuch",
  "газета": "die Zeitung",
  "журнал": "das Magazin",
  "радио": "das Radio",
  "телевизор": "der Fernseher",
  "компьютер": "der Computer",
  "интернет": "das Internet",
  "сайт": "die Webseite",
  "почта (электронная)": "die E-Mail",
  "смартфон": "das Smartphone",
  "ресторан": "das Restaurant",
  "меню": "die Speisekarte",
  "блюдо": "das Gericht",
  "официант": "der Kellner",
  "чаевые": "das Trinkgeld",
  "счет": "die Rechnung",
  "закуска": "die Vorspeise",
  "главное блюдо": "der Hauptgang",
  "десерт": "das Dessert",
  "бутерброд": "das belegte Brötchen",
  "суп": "die Suppe",
  "хлеб": "das Brot",
  "масло": "die Butter",
  "сыр": "der Käse",
  "колбаса": "die Wurst",
  "курица": "das Hähnchen",
  "рыба": "der Fisch",
  "яйцо": "das Ei",
  "рис": "der Reis",
  "лапша": "die Nudeln",
  "мука": "das Mehl",
  "соль": "das Salz",
  "перец": "der Pfeffer",
  "овощи": "das Gemüse",
  "картофель": "die Kartoffel",
  "морковь": "die Karotte",
  "помидор": "die Tomate",
  "огурец": "die Gurke",
  "яблоко": "der Apfel",
  "банан": "die Banane",
  "виноград": "die Traube",
  "апельсин": "die Orange",
  "лимон": "die Zitrone",
  "ананас": "die Ananas",
  "сахар": "der Zucker",
  "мёд": "der Honig",
  "шоколад": "die Schokolade",
  "мороженое": "das Eis",
  "вино": "der Wein",
  "сок": "der Saft",
  "газировка": "das Sodawasser",
  "билет (на транспорт)": "die Fahrkarte",
  "платформа": "der Bahnsteig",
  "расписание": "der Fahrplan",
  "касса": "der Schalter",
  "автобус": "der Bus",
  "самолет": "das Flugzeug",
  "корабль": "das Schiff",
  "маршрут": "die Route",
  "переулок": "die Gasse",
  "проспект": "der Boulevard",
  "квартал": "das Viertel",
  "двор": "der Hof",
  "здание": "das Gebäude",
  "университет": "die Universität",
  "библиотека": "die Bibliothek",
  "музей": "das Museum",
  "театр": "das Theater",
  "церковь": "die Kirche",
  "кафе": "das Café",
  "отель": "das Hotel",
  "поликлиника": "die Poliklinik",
  "почта": "die Post",
  "реклама": "die Werbung",
  "официантка": "die Kellnerin",
  "повар": "der Koch",
  "сотрудник": "der Mitarbeiter",
  "руководитель": "der Leiter",
  "учительница": "die Lehrerin",
  "студентка": "die Studentin",
  "программист": "der Programmierer",
  "письмо": "der Brief",
  "посылка": "das Paket",
  "фотография": "das Foto",
  "телефон": "das Telefon",
  "радиостанция": "der Radiosender",
  "музыка": "die Musik",
  "песня": "das Lied",
  "игра": "das Spiel",
  "спорт": "der Sport",
  "футбол": "der Fußball",
  "баскетбол": "der Basketball",
  "теннис": "das Tennis",
  "бег": "das Laufen",
  "плавание": "das Schwimmen",
  "танцы": "der Tanz",
  "праздник": "das Fest",
  "день рождения": "der Geburtstag",
  "празднование": "die Feier",
  "встреча": "das Treffen",
  "письменный стол": "der Schreibtisch",
  "кровать": "das Bett",
  "диван": "das Sofa",
  "зеркало": "der Spiegel",
  "холодильник": "der Kühlschrank",
  "плита": "der Herd",
  "микроволновка": "die Mikrowelle",
  "посудомоечная машина": "die Spülmaschine",
  "новый": "neu",
  "старый (о вещах)": "alt",
  "дорогой (о цене)": "teuer",
  "дешевый": "billig",
  "красочный": "farbenfroh",

  "счастливый": "glücklich",
  "грустный": "traurig",
  "злой": "böse",
  "радостный": "fröhlich",
  "усталый": "müde",
  "энергичный": "energiegeladen",
  "спокойный": "ruhig",
  "волнующий": "aufregend",
  "интересный": "interessant",
  "скучный": "langweilig",
  "новость": "die Nachricht",
  "событие": "das Ereignis",
  "концерт": "das Konzert",
  "выставка": "die Ausstellung",
  "курс": "der Kurs",
  "урок": "der Unterricht",
  "студия": "das Studio",
  "фабрика": "die Fabrik",
  "семинар": "das Seminar",
  "конференция": "die Konferenz",
  "презентация": "die Präsentation",
  "доклад": "der Vortrag",
  "собрание": "die Versammlung",
  "обсуждение": "die Diskussion",
  "интервью": "das Interview",
  "маркетинг": "das Marketing",
  "покупка": "der Einkauf",
  "цена": "der Preis",
  "выбор": "die Wahl",
  "скидка": "der Rabatt",
  "счёт": "die Rechnung",
  "налог": "die Steuer",
  "инвестиция": "die Investition",
  "прибыль": "der Gewinn",
  "расход": "die Ausgabe",
  "бюджет": "das Budget",
  "банкротство": "die Insolvenz",
  "акция": "die Aktie",
  "рынок": "der Markt",
  "конкуренция": "der Wettbewerb",
  "реклама": "die Werbung",
  "бренд": "die Marke",
  "лидер": "der Marktführer",
  "партнёр": "der Partner",
  "проект": "das Projekt",
  "цель": "das Ziel",
  "стратегия": "die Strategie",
  "план": "der Plan",
  "задача": "die Aufgabe",
  "успех": "der Erfolg",
  "неудача": "das Scheitern",
  "идея": "die Idee",
  "инновация": "die Innovation",
  "технология": "die Technologie",
  "наука": "die Wissenschaft",
  "исследование": "die Forschung",
  "эксперимент": "das Experiment",
  "теория": "die Theorie",
  "факт": "der Fakt",
  "доказательство": "der Beweis",
  "проблема": "das Problem",
  "решение": "die Lösung",
  "метод": "die Methode",
  "система": "das System",
  "структура": "die Struktur",
  "процесс": "der Prozess",
  "параметр": "der Parameter",
  "данные": "die Daten",
  "информация": "die Information",
  "база данных": "die Datenbank",
  "программа": "das Programm",
  "код": "der Code",
  "ошибка": "der Fehler",
  "исправление": "die Korrektur",
  "разработка": "die Entwicklung",
  "обновление": "das Update",
  "версия": "die Version",
  "интерфейс": "die Benutzeroberfläche",
  "функция": "die Funktion",
  "операция": "die Operation",
  "задача": "die Aufgabe",
  "процессор": "der Prozessor",
  "память": "der Speicher",
  "устройство": "das Gerät",
  "клавиатура": "die Tastatur",
  "мышь": "die Maus",
  "монитор": "der Monitor",
  "принтер": "der Drucker",
  "сканер": "der Scanner",
  "интернет": "das Internet",
  "сеть": "das Netzwerk",
  "сервер": "der Server",
  "хостинг": "das Hosting",
  "страница": "die Seite",
  "веб-сайт": "die Webseite",
  "блог": "der Blog",
  "форум": "das Forum",
  "чат": "der Chat",
  "сообщение": "die Nachricht",
  "электронная почта": "die E-Mail",
  "файл": "die Datei",
  "папка": "der Ordner",
  "диск": "die Festplatte",
  "облако": "die Cloud",
  "безопасность": "die Sicherheit",
  "шифрование": "die Verschlüsselung",
  "пароль": "das Passwort",
  "пользователь": "der Benutzer",
  "администратор": "der Administrator",
  "система": "das System",
  "аппарат": "die Hardware",
  "программное обеспечение": "die Software",
  "разработка": "die Entwicklung",
  "тест": "der Test",
  "демо": "das Demo",
  "защита": "der Schutz",
  "вирус": "das Virus",
  "брандмауэр": "die Firewall",
  "антивирус": "das Antivirenprogramm",
  "обновление": "das Update",
  "поддержка": "der Support",
  "проект": "das Projekt",
  "документ": "das Dokument",
  "отчёт": "der Bericht",
  "статистика": "die Statistik",
  "анализ": "die Analyse",
  "отзыв": "das Feedback",
  "рейтинг": "die Bewertung",
  "критика": "die Kritik",
  "рекомендация": "die Empfehlung",
  "статья": "der Artikel",
  "новость": "die Nachricht",
  "журнал": "das Magazin",
  "газета": "die Zeitung",
  "публикация": "die Veröffentlichung",
  "редактор": "der Redakteur",
  "автор": "der Autor",
  "читатель": "der Leser",
  "подписчик": "der Abonnent",
  "комментарий": "der Kommentar",
  "вебинар": "das Webinar",
  "конференция": "die Konferenz",
  "семинар": "das Seminar",
  "курс": "der Kurs",
  "обучение": "die Ausbildung",
  "образование": "die Bildung",
  "школа": "die Schule",
  "университет": "die Universität",
  "факультет": "die Fakultät",
  "кафедра": "das Institut",
  "лекция": "die Vorlesung",
  "практика": "das Praktikum",
  "экзамен": "die Prüfung",
  "тест": "der Test",
  "оценка": "die Note",
  "диплом": "das Diplom",
  "степень": "der Abschluss",
  "сертификат": "das Zertifikat",
  "конкурс": "der Wettbewerb",
  "сессия": "die Prüfungsphase",
  "академия": "die Akademie",
  "искусство": "die Kunst",
  "литература": "die Literatur",
  "история": "die Geschichte",
  "география": "die Geographie",
  "математика": "die Mathematik",
  "физика": "die Physik",
  "химия": "die Chemie",
  "биология": "die Biologie",
  "экономика": "die Wirtschaft",
  "социология": "die Soziologie",
  "психология": "die Psychologie",
  "философия": "die Philosophie",
  "право": "das Recht",
  "политика": "die Politik",
  "государство": "der Staat",
  "правительство": "die Regierung",
  "депутат": "der Abgeordnete",
  "президент": "der Präsident",
  "министр": "der Minister",
  "закон": "das Gesetz",
  "регуляция": "die Regelung",
  "контракт": "der Vertrag",
  "соглашение": "die Vereinbarung",
  "обязанность": "die Pflicht",
  "ответственность": "die Verantwortung",
  "суд": "das Gericht",
  "адвокат": "der Anwalt",
  "дело": "das Verfahren",
  "уголовное дело": "die Straftat",
  "наказание": "die Strafe",
  "преступление": "das Verbrechen",
  "безопасность": "die Sicherheit",
  "оборона": "die Verteidigung",
  "оружие": "die Waffe",
  "война": "der Krieg",
  "мир": "der Frieden",
  "террор": "der Terror",
  "страх": "die Angst",
  "надежда": "die Hoffnung",
  "мечта": "der Traum",
  "любовь": "die Liebe",
  "дружба": "die Freundschaft",
  "семья": "die Familie",
  "отношения": "die Beziehung",
  "брак": "die Ehe",
  "развод": "die Scheidung",
  "ребёнок": "das Kind",
  "воспитание": "die Erziehung",
  "поколение": "die Generation",
  "родственник": "der Verwandte",
  "дядя": "der Onkel",
  "тётя": "die Tante",
  "брат": "der Bruder",
  "сестра": "die Schwester",
  "дедушка": "der Großvater",
  "бабушка": "die Großmutter",

  "утро": "der Morgen",
  "картина": "das Bild",
  "скрипка": "die Geige",
  "гитара": "die Gitarre",
  "барабаны": "die Trommeln",
  "пианино": "das Klavier",
  "паспорт": "der Reisepass",
  "виза": "das Visum",
  "багаж": "das Gepäck",
  "лес": "der Wald",
  "гора": "der Berg",
  "озеро": "der See",
  "река": "der Fluss",
  "пляж": "der Strand",
  "пустыня": "die Wüste",
  "фрукты": "das Obst",
  "радость": "die Freude",
  "печаль": "die Traurigkeit",
  "гнев": "der Zorn",
  "страх": "die Angst",
  "удивление": "die Überraschung",
  "фиолетовый": "violett",
  "оранжевый": "orange",
  "серый": "grau",
  "начинать": "anfangen",
  "заканчивать": "aufhören",
  "продолжать": "fortsetzen",
  "понедельник": "der Montag",
  "вторник": "der Dienstag",
  "среда": "der Mittwoch",
  "четверг": "der Donnerstag",
  "пятница": "der Freitag",
  "суббота": "der Samstag",
  "воскресенье": "der Sonntag",
  "январь": "der Januar",
  "февраль": "der Februar",
  "март": "der März",
  "апрель": "der April",
  "май": "der Mai",
  "июнь": "der Juni",
  "июль": "der Juli",
  "август": "der August",
  "сентябрь": "der September",
  "октябрь": "der Oktober",
  "ноябрь": "der November",
  "декабрь": "der Dezember",
  "преподаватель": "der Dozent",
  "библиотекарь": "der Bibliothekar",
  "сторож": "der Wachmann",
  "рисовать": "zeichnen",
  "петь": "singen",
  "танцевать": "tanzen",
  "смеяться": "lachen",
  "плакать": "weinen",
  "улыбаться": "lächeln",
  "ноутбук": "der Laptop",
  "планшет": "das Tablet",
  "солнечно": "sonnig",
  "облачно": "bewölkt",
  "ветрено": "windig",
  "дождливо": "regnerisch",
  "снежно": "schneereich",
  "хостел": "das Hostel",
  "тур": "die Tour",
  "экскурсия": "die Führung",
  "гид": "der Reiseführer",
  "удовлетворение": "die Zufriedenheit",
  "разочарование": "die Enttäuschung",
  "волнение": "die Aufregung",
  "энтузиазм": "die Begeisterung",
  "лихорадка": "das Fieber",
  "кашель": "der Husten",
  "насморк": "die Erkältung",
  "простуда": "die Grippe",
  "голова": "der Kopf",
  "рука": "die Hand",
  "нога": "das Bein",
  "глаз": "das Auge",
  "ухо": "das Ohr",
  "рот": "der Mund",
  "нос": "die Nase",
  "волосы": "die Haare",
  "сердце": "das Herz",
  "плечо": "die Schulter",
  "налево": "nach links",
  "направо": "nach rechts",
  "прямо": "geradeaus",
  "стакан": "das Glas",
  "ложка": "der Löffel",
  "вилка": "die Gabel",
  "нож": "das Messer",
  "тарелка": "der Teller",
  "чашка": "die Tasse",
  "помогать": "helfen",
  "забывать": "vergessen",
  "помнить": "erinnern",
  "надеяться": "hoffen",
  "желать": "wünschen",
  "рассказывать": "erzählen",
  "спрашивать": "fragen",
  "отвечать": "antworten",
  "изучать": "studieren",
  "трудный": "schwierig",
  "легкий": "einfach",
  "важный": "wichtig",
  "известный": "bekannt",
  "знаменитый": "berühmt",

  "птица": "der Vogel",
  "обезьяна": "der Affe",
  "корова": "die Kuh",
  "свинья": "das Schwein",
  "овца": "das Schaf",
  "кролик": "das Kaninchen",
  "пчела": "die Biene",
  "муравей": "die Ameise",
  "слон": "der Elefant",
  "тигр": "der Tiger",
  "лев": "der Löwe",
  "змея": "die Schlange",
  "лягушка": "der Frosch",
  "рысь": "der Luchs",
  "барс": "der Leopard",
  "волк": "der Wolf",
  "лиса": "der Fuchs",
  "заяц": "der Hase",
  "белка": "das Eichhörnchen",
  "еж": "der Igel",
  "паука": "die Spinne",
  "насекомое": "das Insekt",
  "пыль": "der Staub",
  "грязь": "der Schmutz",
  "ветер": "der Wind",
  "туман": "der Nebel",
  "холод": "die Kälte",
  "тепло": "die Wärme",
  "влажность": "die Feuchtigkeit",
  "погода": "das Wetter",
  "радуга": "der Regenbogen",
  "луна": "der Mond",
  "планета": "der Planet",
  "космос": "der Weltraum",
  "земля": "die Erde",
  "долина": "das Tal",
  "водопад": "der Wasserfall",
  "берег": "das Ufer",
  "остров": "die Insel",
  "море": "das Meer",
  "океан": "der Ozean",
  "залив": "die Bucht",
  "континент": "der Kontinent",
  "поле": "das Feld",
  "луг": "die Wiese",
  "фрукт": "die Frucht",
  "ягода": "die Beere",
  "пиво": "das Bier",
  "водка": "der Wodka",
  "вилка": "die Gabel",
  "ложка": "der Löffel",
  "нож": "das Messer",
  "тарелка": "der Teller",
  "бутылка": "die Flasche",
  "супница": "die Suppenschüssel",
  "сковорода": "die Pfanne",
  "кастрюля": "der Topf",
  "миксер": "der Mixer",
  "духовка": "der Ofen",
  "чайник": "der Wasserkocher",
  "соковыжималка": "der Entsafter",
  "блендер": "der Mixer",
  "шкаф": "der Schrank",
  "полка": "das Regal",
  "картина": "das Gemälde",
  "ковёр": "der Teppich",
  "подушка": "das Kissen",
  "одеяло": "die Decke",
  "покрывало": "der Überwurf",
  "занавески": "die Gardinen",
  "свет": "das Licht",
  "принтер": "der Drucker",
  "сканер": "der Scanner",
  "факс": "das Faxgerät",
  "энциклопедия": "die Enzyklopädie",
  "объявление": "die Anzeige",
  "денежный перевод": "die Überweisung",
  "кредит": "der Kredit",
  "долг": "die Schuld",
  "инвестиция": "die Investition",
  "расход": "die Ausgabe",
  "бюджет": "das Budget",
  "финансы": "die Finanzen",
  "предприниматель": "der Unternehmer",
  "проектор": "der Projektor",
  "рейтинг": "das Rating",
  "рецензия": "die Rezension",
  "отзыв": "das Feedback",
  "курсы": "die Kurse",
  "конференция": "die Konferenz",
  "встреча": "das Treffen",
  "задание": "die Aufgabe",
  "диплом": "das Diplom",
  "факультет": "die Fakultät",
  "кафедра": "das Institut",
  "лекция": "die Vorlesung",
  "практика": "das Praktikum",
  "профессор": "der Professor",
  "обучение": "die Ausbildung",
  "образование": "die Bildung",
  "исследование": "die Forschung",
  "эксперимент": "das Experiment",
  "теория": "die Theorie",
  "факт": "der Fakt",
  "доказательство": "der Beweis",

  
  "спальня": "das Schlafzimmer",
  "ванная": "das Badezimmer",
  "кухня": "die Küche",
  "гостиная": "das Wohnzimmer",
  "коридор": "der Flur",
  "балкон": "der Balkon",
  "лифт": "der Aufzug",
  "гараж": "die Garage",
  "футболка": "das T-Shirt",
  "джинсы": "die Jeans",
  "брюки": "die Hose",
  "юбка": "der Rock",
  "пиджак": "das Sakko",
  "куртка": "die Jacke",
  "шапка": "die Mütze",
  "перчатки": "die Handschuhe",
  "обувь": "die Schuhe",
  "носки": "die Socken",
  "рубашка": "das Hemd",
  "платье": "das Kleid",
  "свитер": "der Pullover",
  "пальто": "der Mantel",
  "кольцо": "der Ring",
  "ожерелье": "die Kette",
  "браслет": "das Armband",
  "часы": "die Uhr",
  "очки": "die Brille",
  "сумка": "die Tasche",
  "кошелек": "das Portemonnaie",
  "ремень": "der Gürtel",
  "галстук": "die Krawatte",
  "шарф": "der Schal",
  "кровать": "das Bett",
  "диван": "das Sofa",
  "кресло": "der Sessel",
  "зеркало": "der Spiegel",
  "шкаф": "der Schrank",
  "комод": "die Kommode",
  "одеяло": "die Decke",
  "подушка": "das Kissen",
  "занавески": "die Vorhänge",
  "ковёр": "der Teppich",
  "стена": "die Wand",
  "потолок": "die Decke",
  "пол": "der Boden",
  "окно": "das Fenster",
  "дверь": "die Tür",
  "лампа": "die Lampe",
  "микроволновка": "die Mikrowelle",
  "холодильник": "der Kühlschrank",
  "плита": "der Herd",
  "стиральная машина": "die Waschmaschine",
  "посудомоечная машина": "die Spülmaschine",
  "пылесос": "der Staubsauger",
  "телевизор": "der Fernseher",
  "радио": "das Radio",
  "компьютер": "der Computer",
  "ноутбук": "der Laptop",
  "планшет": "das Tablet",
  "принтер": "der Drucker",
  "сканер": "der Scanner",
  "фотокамера": "die Kamera",
  "фотоаппарат": "die Kamera",
  "микрофон": "das Mikrofon",
  "колонка": "der Lautsprecher",
  "наушники": "die Kopfhörer",
  "интернет": "das Internet",
  "сеть": "das Netzwerk",
  "маршрутизатор": "der Router",
  "программа": "das Programm",
  "приложение": "die Anwendung",
  "игра": "das Spiel",
  "файл": "die Datei",
  "папка": "der Ordner",
  "документ": "das Dokument",
  "презентация": "die Präsentation",
  "почта": "die Post",
  "сообщение": "die Nachricht",
  "чат": "der Chat",
  "блог": "der Blog",
  "видео": "das Video",
  "фильм": "der Film",
  "сериал": "die Serie",
  "музыка": "die Musik",
  "песня": "das Lied",
  "радиостанция": "der Radiosender",
  "подкаст": "der Podcast",
  "журнал": "das Magazin",
  "газета": "die Zeitung",

  "бронирование": "die Reservierung",
  "авиабилет": "das Flugticket",
  "отмена": "die Stornierung",
  "поездка": "die Fahrt",
  "маршрут": "die Route",
  "карьерный рост": "der Karriereaufstieg",
  "совещание": "das Meeting",
  "контакт": "der Kontakt",
  "продукция": "das Produkt",
  "товар": "die Ware",
  "производство": "die Produktion",
  "предприятие": "das Unternehmen",
  "сотрудничество": "die Zusammenarbeit",
  "расширение": "die Expansion",
  "прогноз": "die Prognose",
  "производительность": "die Produktivität",
  "промоция": "die Promotion",
  "галерея": "die Galerie",
  "архив": "das Archiv",
  "источник": "die Quelle",
  "форум": "das Forum",
  "сообщество": "die Gemeinschaft",
  "культура": "die Kultur",
  "традиция": "die Tradition",
  "диалект": "der Dialekt",
  "перевод": "die Übersetzung",
  "грамматика": "die Grammatik",
  "правописание": "die Rechtschreibung",
  "произношение": "die Aussprache",
  "упражнение": "die Übung",
  "учеба": "das Studium",
  "карьера": "die Karriere",
  "доска": "die Tafel",
  "ручка": "der Kugelschreiber",
  "карандаш": "der Bleistift",
  "тетрадь": "das Heft",
  "маркер": "der Marker",
  "бумага": "das Papier",
  "закладка": "das Lesezeichen",
  "класс": "das Klassenzimmer",
  "домашнее задание": "die Hausaufgabe",
  "преподаватель": "der Dozent",
  "доктор": "der Doktor",
  "лекарство": "das Medikament",
  "рецепт": "das Rezept",
  "операция": "die Operation",
  "терапия": "die Therapie",
  "симптом": "das Symptom",
  "диагноз": "die Diagnose",
  "жалоба": "die Beschwerde",
  "ускорение": "die Beschleunigung",
  "страховка": "die Versicherung",
  "турист": "der Tourist",
  "сервис": "der Service",
  "качество": "die Qualität",
  "гарантия": "die Garantie",
  "возврат": "die Rückgabe",
  "доставка": "die Lieferung",
  "оплата": "die Bezahlung",
  "платеж": "die Zahlung",
  "налог": "die Steuer",
  "счёт (банк)": "das Konto",
  "кредитная карта": "die Kreditkarte",
  "банкомат": "der Geldautomat",
  "доллар": "der Dollar",
  "евро": "der Euro",
  "фунт": "das Pfund",
  "валюта": "die Währung",
  "акция": "die Aktie",
  "биржа": "die Börse",
  "предприятие": "das Unternehmen",
  "товар": "die Ware",
  "учеба": "das Studium",
  "документ": "das Dokument",
  "презентация": "die Präsentation",
  "почта": "die Post",
  "сообщение": "die Nachricht",
  "чат": "der Chat",

  "спортсмен": "der Sportler",
  "тренер": "der Trainer",
  "команда": "das Team",
  "соревнование": "der Wettkampf",
  "победа": "der Sieg",
  "поражение": "die Niederlage",
  "ничья": "das Unentschieden",
  "тренировка": "das Training",
  "судья": "der Schiedsrichter",
  "фанат": "der Fan",
  "зритель": "der Zuschauer",
  "участник": "der Teilnehmer",
  "компания": "die Firma",
  "союз": "der Bund",
  "партия": "die Partei",
  "выборы": "die Wahlen",
  "голосовать": "wählen",
  "республика": "die Republik",
  "монархия": "die Monarchie",
  "конституция": "die Verfassung",
  "демократия": "die Demokratie",
  "свобода": "die Freiheit",
  "парламент": "das Parlament",
  "нация": "die Nation",
  "общество": "die Gesellschaft",
  "мода": "die Mode",
  "стиль": "der Stil",
  "тренд": "der Trend",
  "коллекция": "die Kollektion",
  "магазин одежды": "das Bekleidungsgeschäft",
  "модель": "das Modell",
  "примерка": "die Anprobe",
  "фестиваль": "das Festival",
  "карнавал": "der Karneval",
  "новый год": "das Neujahr",
  "рождество": "Weihnachten",
  "пасха": "das Osterfest",
  "свадьба": "die Hochzeit",
  "юбилей": "das Jubiläum",
  "поздравление": "der Glückwunsch",
  "решать": "entscheiden",
  "подписывать": "unterschreiben",
  "переулок": "die Gasse",
  "шоссе": "die Landstraße",
  "транспорт": "der Transport",
  "движение": "die Bewegung",
  "направление": "die Richtung",
  "поворот": "die Kurve",
  "остановка": "die Haltestelle",
  "вход": "der Eingang",
  "выход": "der Ausgang",
  "линия": "die Linie",
  "переход": "der Übergang",
  "подъезд": "der Eingang",
  "этаж": "der Stock",
  "эскалатор": "die Rolltreppe",
  "село": "das Dorf",
  "регион": "die Region",
  "национальный": "national",
  "местный": "lokal",
  "городской": "städtisch",
  "деревенский": "ländlich",
  "современный": "modern",
  "старомодный": "altmodisch",
  "технологичный": "technologisch",
  "быстрый": "schnell",
  "медленный": "langsam",
  "серьезный": "ernst",
  "забавный": "amüsant",
  "умный": "klug",
  "глупый": "dumm",
  "трудолюбивый": "fleißig",
  "ленивый": "faul",
  "чистый": "sauber",
  "грязный": "schmutzig",
  "богатый": "reich",
  "бедный": "arm",
  "симпатичный": "hübsch",
  "сложный": "kompliziert",
  "неважный": "unwichtig",
  "надежный": "zuverlässig",
  "ненадежный": "unzuverlässig",
  "твердый": "hart",
  "мягкий": "weich",
  "горячий": "heiß",
  "холодный": "kalt",
  "сладкий": "süß",
  "горький": "bitter",
  "кислый": "sauer",
  "солёный": "salzig",
  "спортсменка": "die Sportlerin",
  "тренировка (спорт)": "das Training",
  "интервал": "das Intervall",
  "поддерживать": "unterstützen",
  "образ": "das Image",
  "мода (стиль)": "die Mode",
  "тренд (новинка)": "der Trend",
  "коллекция (одежды)": "die Kollektion",
  "союз (объединение)": "die Union",
  "голос (звучание)": "die Stimme",
  "пародия": "die Parodie",
  "юмор": "der Humor",
  "концепция": "das Konzept",
  "искусство": "die Kunst",
  "литература": "die Literatur",
  "поэзия": "die Poesie",
  "драма": "das Drama",
  "комедия": "die Komödie",
  "фантастика": "die Fantasie",
  "научная фантастика": "die Science-Fiction",
  "биография": "die Biographie",
  "автобиография": "die Autobiographie",
  "эпоха": "die Epoche",
  "традиция": "die Tradition",
  "обряд": "das Ritual",
  "миф": "der Mythos",
  "легенда": "die Legende",
  "предание": "die Sage",
  "образование": "die Bildung",
  "наука": "die Wissenschaft",
  "технология": "die Technologie",
  "информация": "die Information",
  "данные": "die Daten",
  "программа": "das Programm",
  "код": "der Code",
  "ошибка": "der Fehler",
  "исправление": "die Korrektur",
  "тестирование": "das Testen",
  "интерфейс": "die Benutzeroberfläche",
  "функция": "die Funktion",
  "операция": "die Operation",
  "процессор": "der Prozessor",
  "память": "der Speicher",
  "устройство": "das Gerät",
  "клавиатура": "die Tastatur",
  "мышь": "die Maus",
  "монитор": "der Monitor",
  "сервер": "der Server",
  "хостинг": "das Hosting",
  "веб-сайт": "die Webseite",
  "форум": "das Forum",
  "блог": "der Blog",
  "чат": "der Chat",
  "файл": "die Datei",
  "папка": "der Ordner",
  "документ": "das Dokument",
  "презентация": "die Präsentation",
  "сообщение": "die Nachricht"
};
